[project]
name = "trajectory-api"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.14",
    "fastapi[all]>=0.115.12",
    "pytest>=8.4.1",
]
